title: Mark Fleming Blog
logo: logo.png
author: 
  name: Mark Fleming
  email: mdfleming3@gmail.com
description: Practical Marketing Solutions - This blog gives best practices on content, digital, analytics, and marketing strategy.

#Google Analytics
google_analytics: UA-172446520-1

show_excerpts: true # set to true to show excerpts on the homepage

# Specify the name of a file to show as a masthead graphic at the top of each page, instead of a title, here:
masthead: logo.png

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: markdfleming2
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    instagram: markdfleming
    linkedin: markdfleming
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

addthis: true

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
- subscribe.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

gems: 
 - jekyll-sitemap
 - 'jekyll-feed'
 
permalink: /:title/
